export const LOGIN_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const LOGIN_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const LOGIN_FAIL = 'PRODUCT_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
